#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have some other compatible shell such as ksh or
#       bash, then you can try running this script with the other shell, or you
#       can attempt to locate the executable yourself.
#
#   (2) Ideally, you would put the Gradle wrapper distribution somewhere safe
#       (e.g. inside the project) to avoid having to continually download it.
#       See https://docs.gradle.org/8.4/userguide/gradle_wrapper.html for more details.
#
#   (3) This script is generated by the Gradle wrapper task. Do not edit this file
#       directly; instead edit the Gradle wrapper configuration file or regenerate
#       this script.
#
#   (4) Along with the Gradle wrapper, this project also includes a gradlew.bat
#       batch script, which should be used on Windows.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME-.}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export APP_HOME
export APP_NAME
export APP_BASE_NAME

case "$1" in
  --help )
    echo "Gradle wrapper script for POSIX generated by Gradle."
    echo ""
    echo "Optional arguments:"
    echo "  --app-home   Set the value of APP_HOME"
    echo "  --debug      Set the value of DEBUG to true"
    echo "  --info       Set the value of INFO to true"
    echo ""
    exit 0
    ;;
  --debug )
    APP_DEBUG=true
    shift
    ;;
  --info )
    APP_INFO=true
    shift
    ;;
 esac

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$( uname )" = 'CYGWIN' ] || [ "$( uname )" = 'MSYS' ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    APP_BASE_NAME=$( cygpath --path --mixed "$APP_BASE_NAME" )
export APP_HOME
    export APP_BASE_NAME
fi

DEFAULT_JVM_OPTS='" -Xmx64m" "-Xms64m"'
JAVA_OPTS="${JAVA_OPTS} ${DEFAULT_JVM_OPTS}"

# When using the daemon, arguments passed to gradle must start with a '-' or be valid class/method names.
# Clean up by removing the object files you may have created in the process
if [ -n "$APP_BASE_NAME" ] ; then
    exec "$JAVA_HOME/bin/java" $JAVA_OPTS -classpath "$(find . -name 'gradle-wrapper.jar' | head -1)" org.gradle.wrapper.GradleWrapperMain "$@"
else
    exec "$JAVA_HOME/bin/java" $JAVA_OPTS org.gradle.wrapper.GradleWrapperMain "$@"
fi
